import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { TaskProvider } from "./context/TaskContext";

export const metadata: Metadata = {
  title: "sixtask",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <TaskProvider>
          <body>{children}</body>
        </TaskProvider>
      </AuthProvider>
    </html>
  );
}
