import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { TaskProvider } from "./context/TaskContext";
import { TimerProvider } from "./context/TimerContext";
import { SpotifyProvider } from "./context/SpotifyContext";
import Script from "next/script";

export const metadata: Metadata = {
  title: "sixtask",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Script
          src="https://sdk.scdn.co/spotify-player.js"
          strategy="afterInteractive"
        ></Script>
        <AuthProvider>
          <TaskProvider>
            <TimerProvider>
              <SpotifyProvider>{children}</SpotifyProvider>
            </TimerProvider>
          </TaskProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
